<div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Listado de Tickets</h1>
        <!-- DataTales Example -->

        <div class="card shadow mb-4">
          <div class="card-body">
            <form method="post">
              <div class="input-group mb-3">
                <input 
                  name="fecha" 
                  type="text" 
                  class="form-control datepicker" 
                  autocomplete="off" 
                  value="<?php echo $this->fecha; ?>"
                  readonly >
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
                    | Buscar
                  </button>
                </div>
              </div>
            </form>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTableEsp" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Ticket</th>
                    <th>Tipo Veh&iacute;culo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Fecha</th>
                    <th>Ticket</th>
                    <th>Tipo Veh&iacute;culo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
                  <?php foreach ($this->tickets as $key => $value) { ?>
                  <tr>
                    <td><?php echo $value->getFechaIngreso()->format('d/m/Y h:i:s a'); ?></td>
                    <td><?php echo $value->getNumero(); ?></td>
                    <td><?php echo $value->getTipo()->getDescripcion(); ?></td>
                    <td>
                    <?php
                    $temp = false; 
                    if(count($value->getIngresoNormal()[0]->getNoPagos())){
                      $temp = true;
                      echo "PASE CORTESIA";
                    }else if(count($value->getIngresoNormal()[0]->getPagos())){
                      $temp = true;
                      echo "PAGADO";
                    }else if(count($value->getIngresoNormal()[0]->getCancelados())){
                      $temp = true;
                      echo "ANULADO";
                    }else{
                      echo "ACTIVO";
                    }
                    ?>
                    </td>
                    <td class="text-center">
                      <?php if(!$temp){ ?>
                      <a 
                        title="Pase Cortesia" 
                        href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>pasecortesia/<?php echo $value->getId(); ?>/">
                          <i class="far fa-share-square"></i>
                      </a>
                      <a 
                        title="Anular Ticket" 
                        href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>anular/<?php echo $value->getId(); ?>/">
                          <i class="far fa-thumbs-down"></i>
                      </a>
                      <?php } ?>
                    </td>
                  </tr>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>


</div>