<style>
    .modal-dialog {
    max-width: 700px !important;
  }
  </style>
<div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Listado de Tickets</h1>
        <!-- DataTales Example -->

        <div class="card shadow mb-4">
          <div class="card-body">
            <form method="post">
              <div class="input-group mb-3">
                <input 
                  name="fecha" 
                  type="text" 
                  class="form-control datepicker" 
                  autocomplete="off" 
                  value="<?php echo $this->fecha; ?>"
                  readonly >
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
                    | Buscar
                  </button>
                </div>
              </div>
            </form>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTableEsp" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Ticket</th>
                    <th>Tipo Veh&iacute;culo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Fecha</th>
                    <th>Ticket</th>
                    <th>Tipo Veh&iacute;culo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
                  <?php foreach ($this->tickets as $key => $value) { ?>
                  <tr>
                    <td><?php echo $value->getFechaIngreso()->format('d/m/Y h:i:s a'); ?></td>
                    <td><?php echo $value->getNumero(); ?></td>
                    <td><?php echo $value->getTipo()->getDescripcion(); ?></td>
                    <td>
                    <?php
                    $temp = false; 
                    if(count($value->getIngresoNormal()[0]->getNoPagos())){
                      $temp = true;
                      echo "PASE CORTESIA";
                    }else if(count($value->getIngresoNormal()[0]->getPagos())){
                      $temp = true;
                      echo "PAGADO";
                    }else if(count($value->getIngresoNormal()[0]->getCancelados())){
                      $temp = true;
                      echo "ANULADO";
                    }else{
                      echo "ACTIVO";
                    }
                    ?>
                    </td>
                    <td class="text-center">
                      <a 
                        title="Imprimir Ticket" 
                        href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>imprimir/<?php echo $value->getNumero(); ?>/">
                          <i class="fas fa-fingerprint"></i>
                      </a>

                      <?php if(count($value->getIngresoNormal()[0]->getPagos())){ ?>
                        <a 
                          title="Descargar Factura" 
                          href="<?php echo BASE_URL.'pago/'; ?>generarFactura/<?php echo $value->getNumero(); ?>/">
                          <i class="fas fa-print"></i>
                        </a>
                      <?php } ?>  

                      <?php if(!$temp){ ?>
                      <a 
                        title="Pase Cortesia" 
                        href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>pasecortesia/<?php echo $value->getId(); ?>/">
                          <i class="far fa-share-square"></i>
                      </a>
                      <a 
                        title="Anular Ticket" 
                        href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>anular/<?php echo $value->getId(); ?>/">
                          <i class="far fa-thumbs-down"></i>
                      </a>
                      <?php } ?>
                      <a class="photo"
                        title="Fotos" 
                        href=""
                        ticket="<?php echo $value->getNumero(); ?>">
                          <i class="far fa-images"></i>
                      </a>
                    </td>
                  </tr>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>


</div>

<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" id="modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Fotos Ticket</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="card">
            <div class="card-header">
              <ul class="nav nav-tabs card-header-tabs" id="photo-list" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" href="#entrada" role="tab" aria-controls="entrada" aria-selected="true">Entrada</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link"  href="#salida" role="tab" aria-controls="salida" aria-selected="false">Salida</a>
                </li>
              </ul>
            </div>
            <div class="card-body">
               <div class="tab-content mt-3">
                <div class="tab-pane active" id="entrada" role="tabpanel">
                  <img id="imgPhotoIn" src="" alt="..." class="img-thumbnail" onerror="this.src='<?php echo BASE_URL ?>public/img/imagen-no-disponible.jpg'">
                </div>
                <div class="tab-pane" id="salida" role="tabpanel">  
                  <img id="imgPhotoOut" src="" alt="..." class="img-thumbnail" onerror="this.src='<?php echo BASE_URL ?>public/img/imagen-no-disponible.jpg'">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          
        </div>
      </div>
    </div>
  </div>