/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-jun.-2019 9:12:25 p.m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `accesocaja` CASCADE
;

DROP TABLE IF EXISTS `caja` CASCADE
;

DROP TABLE IF EXISTS `cliente` CASCADE
;

DROP TABLE IF EXISTS `ingreso` CASCADE
;

DROP TABLE IF EXISTS `ingresonormal` CASCADE
;

DROP TABLE IF EXISTS `ingresotarjeta` CASCADE
;

DROP TABLE IF EXISTS `pago` CASCADE
;

DROP TABLE IF EXISTS `pagomensual` CASCADE
;

DROP TABLE IF EXISTS `pagoservicio` CASCADE
;

DROP TABLE IF EXISTS `rol` CASCADE
;

DROP TABLE IF EXISTS `tarifa` CASCADE
;

DROP TABLE IF EXISTS `tarjeta` CASCADE
;

DROP TABLE IF EXISTS `tipocliente` CASCADE
;

DROP TABLE IF EXISTS `tipotarifa` CASCADE
;

DROP TABLE IF EXISTS `tipovehiculo` CASCADE
;

DROP TABLE IF EXISTS `usuario` CASCADE
;

DROP TABLE IF EXISTS `usuariorol` CASCADE
;

/* Create Tables */

CREATE TABLE `accesocaja`
(
	`caja` INT NOT NULL,
	`usuario` INT NOT NULL,
	`fechainicio` DATETIME NOT NULL,
	`fechacierre` DATETIME NULL,
	`totalrecibido` DECIMAL(8,0) NULL COMMENT 'Almacena el total de la caja al momento del cierre',
	`totalcierre` DECIMAL(8,0) NULL,
	CONSTRAINT `PK_accesocaja` PRIMARY KEY (`caja` ASC, `usuario` ASC, `fechainicio` ASC)
)

;

CREATE TABLE `caja`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(100) NULL,
	CONSTRAINT `PK_caja` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `cliente`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`documento` VARCHAR(20) NULL,
	`nombre` VARCHAR(50) NULL,
	`fechanacimiento` DATE NULL,
	`direccion` VARCHAR(50) NULL,
	`telefono` VARCHAR(20) NULL,
	`email` VARCHAR(50) NULL,
	`tipocliente` INT NULL COMMENT 'Almacena información de los tipos de clientes',
	`usuario` INT NULL COMMENT 'Almacena el id del usuario que registro al cliente',
	CONSTRAINT `PK_cliente` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `ingreso`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`tipovehiculo` INT NULL,
	`fechaingreso` DATETIME NULL,
	`fechasalida` DATETIME NULL,
	`numero` VARCHAR(10) NULL COMMENT 'Almacena el numero o identificacion del ticket para el codigo de barra',
	CONSTRAINT `PK_ingreso` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena la información de los ingresos al uso del parqueadero por parte de los vehiculos.'

;

CREATE TABLE `ingresonormal`
(
	`id` INT NOT NULL,
	CONSTRAINT `PK_ingresonormal` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `ingresotarjeta`
(
	`id` INT NOT NULL,
	`tarjeta` VARCHAR(50) NULL,
	CONSTRAINT `PK_ingresotarjeta` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `pago`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`fecha` DATETIME NULL,
	`valor` DECIMAL(8,0) NULL,
	`ingreso` INT NULL,
	`usuario` INT NULL,
	`caja` INT NULL,
	CONSTRAINT `PK_pago` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena la información de los pagos del ingreso'

;

CREATE TABLE `pagomensual`
(
	`id` INT NOT NULL,
	`tarjeta` VARCHAR(50) NULL,
	`valor` DECIMAL(10,0) NULL,
	`fecha` DATE NULL,
	`fecharegistro` DATETIME NULL,
	CONSTRAINT `PK_pagomensual` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `pagoservicio`
(
	`id` INT NOT NULL,
	`ingreso` INT NULL,
	CONSTRAINT `PK_pagoservicio` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `rol`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(100) NULL,
	CONSTRAINT `PK_rol` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `tarifa`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(100) NULL,
	`fechainicio` DATE NULL,
	`fechafin` DATE NULL,
	`valor` DECIMAL(9,0) NULL,
	`tipovehiculo` INT NULL,
	`tipotarifa` INT NULL,
	CONSTRAINT `PK_tarifa` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena la información de las tarifas por el uso del servicio de parqueader de los distintos tipos de vehiculo'

;

CREATE TABLE `tarjeta`
(
	`rfid` VARCHAR(50) NOT NULL,
	`estado` INT NULL,
	`fechainicio` DATE NULL,
	`fechafin` DATE NULL,
	`usuarioactivo` INT NULL,
	`cliente` INT NULL,
	`tipovehiculo` INT NULL,
	CONSTRAINT `PK_tarjeta` PRIMARY KEY (`rfid` ASC)
)

;

CREATE TABLE `tipocliente`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(50) NULL,
	CONSTRAINT `PK_tipocliente` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `tipotarifa`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(50) NULL,
	CONSTRAINT `PK_tipotarifa` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena los distintos tipos de tarifas que hay'

;

CREATE TABLE `tipovehiculo`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(50) NULL,
	CONSTRAINT `PK_tipovehiculo` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena la información del tipo de vehiculo que puede ingresar al parqueadero'

;

CREATE TABLE `usuario`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`usuario` VARCHAR(20) NULL,
	`clave` VARCHAR(100) NULL,
	`email` VARCHAR(50) NULL,
	`nombre` VARCHAR(50) NULL,
	`documento` VARCHAR(20) NULL,
	`fechanacimiento` DATE NULL,
	`rol` INT NULL,
	CONSTRAINT `PK_usuario` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Almacena la información del usuario'

;

CREATE TABLE `usuariorol`
(
	`idrol` INT NOT NULL,
	`idusuario` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`idrol` ASC, `idusuario` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `accesocaja` 
 ADD INDEX `IXFK_accesocaja_caja` (`caja` ASC)
;

ALTER TABLE `accesocaja` 
 ADD INDEX `IXFK_accesocaja_usuario` (`usuario` ASC)
;

ALTER TABLE `cliente` 
 ADD INDEX `IXFK_cliente_tipocliente` (`tipocliente` ASC)
;

ALTER TABLE `cliente` 
 ADD INDEX `IXFK_cliente_usuario` (`usuario` ASC)
;

ALTER TABLE `ingreso` 
 ADD INDEX `IXFK_ingreso_tipovehiculo` (`tipovehiculo` ASC)
;

ALTER TABLE `ingresonormal` 
 ADD INDEX `IXFK_ingresonormal_ingreso` (`id` ASC)
;

ALTER TABLE `ingresotarjeta` 
 ADD INDEX `IXFK_ingresotarjeta_ingreso` (`id` ASC)
;

ALTER TABLE `ingresotarjeta` 
 ADD INDEX `IXFK_ingresotarjeta_tarjeta` (`tarjeta` ASC)
;

ALTER TABLE `pago` 
 ADD INDEX `IXFK_pago_caja` (`caja` ASC)
;

ALTER TABLE `pago` 
 ADD INDEX `IXFK_pago_ingresonormal` (`ingreso` ASC)
;

ALTER TABLE `pago` 
 ADD INDEX `IXFK_pago_usuario` (`usuario` ASC)
;

ALTER TABLE `pagomensual` 
 ADD INDEX `IXFK_pagomensual_pago` (`id` ASC)
;

ALTER TABLE `pagomensual` 
 ADD INDEX `IXFK_pagomensual_tarjeta` (`tarjeta` ASC)
;

ALTER TABLE `pagoservicio` 
 ADD INDEX `IXFK_pagoservicio_ingresonormal` (`ingreso` ASC)
;

ALTER TABLE `pagoservicio` 
 ADD INDEX `IXFK_pagoservicio_pago` (`id` ASC)
;

ALTER TABLE `tarifa` 
 ADD INDEX `IXFK_tarifa_tipotarifa` (`tipotarifa` ASC)
;

ALTER TABLE `tarifa` 
 ADD INDEX `IXFK_tarifa_tipovehiculo` (`tipovehiculo` ASC)
;

ALTER TABLE `tarjeta` 
 ADD INDEX `IXFK_tarjeta_cliente` (`cliente` ASC)
;

ALTER TABLE `tarjeta` 
 ADD INDEX `IXFK_tarjeta_tipovehiculo` (`tipovehiculo` ASC)
;

ALTER TABLE `tarjeta` 
 ADD INDEX `IXFK_tarjeta_usuario` (`usuarioactivo` ASC)
;

ALTER TABLE `usuario` 
 ADD INDEX `IXFK_usuario_rol` (`rol` ASC)
;

ALTER TABLE `usuariorol` 
 ADD INDEX `IXFK_usuariorol_rol` (`idrol` ASC)
;

ALTER TABLE `usuariorol` 
 ADD INDEX `IXFK_usuariorol_usuario` (`idusuario` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `accesocaja` 
 ADD CONSTRAINT `FK_accesocaja_caja`
	FOREIGN KEY (`caja`) REFERENCES `caja` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `accesocaja` 
 ADD CONSTRAINT `FK_accesocaja_usuario`
	FOREIGN KEY (`usuario`) REFERENCES `usuario` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `cliente` 
 ADD CONSTRAINT `FK_cliente_tipocliente`
	FOREIGN KEY (`tipocliente`) REFERENCES `tipocliente` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `cliente` 
 ADD CONSTRAINT `FK_cliente_usuario`
	FOREIGN KEY (`usuario`) REFERENCES `usuario` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ingresonormal` 
 ADD CONSTRAINT `FK_ingresonormal_ingreso`
	FOREIGN KEY (`id`) REFERENCES `ingreso` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ingresotarjeta` 
 ADD CONSTRAINT `FK_ingresotarjeta_ingreso`
	FOREIGN KEY (`id`) REFERENCES `ingreso` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ingresotarjeta` 
 ADD CONSTRAINT `FK_ingresotarjeta_tarjeta`
	FOREIGN KEY (`tarjeta`) REFERENCES `tarjeta` (`rfid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pago` 
 ADD CONSTRAINT `FK_pago_caja`
	FOREIGN KEY (`caja`) REFERENCES `caja` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pago` 
 ADD CONSTRAINT `FK_pago_usuario`
	FOREIGN KEY (`usuario`) REFERENCES `usuario` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pagomensual` 
 ADD CONSTRAINT `FK_pagomensual_pago`
	FOREIGN KEY (`id`) REFERENCES `pago` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pagomensual` 
 ADD CONSTRAINT `FK_pagomensual_tarjeta`
	FOREIGN KEY (`tarjeta`) REFERENCES `tarjeta` (`rfid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pagoservicio` 
 ADD CONSTRAINT `FK_pagoservicio_ingresonormal`
	FOREIGN KEY (`ingreso`) REFERENCES `ingresonormal` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pagoservicio` 
 ADD CONSTRAINT `FK_pagoservicio_pago`
	FOREIGN KEY (`id`) REFERENCES `pago` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tarifa` 
 ADD CONSTRAINT `FK_tarifa_tipotarifa`
	FOREIGN KEY (`tipotarifa`) REFERENCES `tipotarifa` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tarifa` 
 ADD CONSTRAINT `FK_tarifa_tipovehiculo`
	FOREIGN KEY (`tipovehiculo`) REFERENCES `tipovehiculo` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tarjeta` 
 ADD CONSTRAINT `FK_tarjeta_cliente`
	FOREIGN KEY (`cliente`) REFERENCES `cliente` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tarjeta` 
 ADD CONSTRAINT `FK_tarjeta_tipovehiculo`
	FOREIGN KEY (`tipovehiculo`) REFERENCES `tipovehiculo` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tarjeta` 
 ADD CONSTRAINT `FK_tarjeta_usuario`
	FOREIGN KEY (`usuarioactivo`) REFERENCES `usuario` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `FK_usuario_rol`
	FOREIGN KEY (`rol`) REFERENCES `rol` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuariorol` 
 ADD CONSTRAINT `FK_usuariorol_rol`
	FOREIGN KEY (`idrol`) REFERENCES `rol` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuariorol` 
 ADD CONSTRAINT `FK_usuariorol_usuario`
	FOREIGN KEY (`idusuario`) REFERENCES `usuario` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
