<div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Listado de Pagos Mensuales</h1>
        <!-- DataTales Example -->

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <div class="float-sm-right">
              <a href="<?php echo BASE_URL ?>pago/registrarmensual/" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                  <i class="fas fa-check"></i>
                </span>
                <span class="text">Registrar Pago Mensual</span>
              </a>
            </div>
          </div>
          <div class="card-body">
            <form method="post">
              <div class="input-group mb-3">
                <input name="fecha" type="text" class="form-control datepicker" 
                  autocomplete="off" 
                  value="<?php echo $this->fecha; ?>" readonly >
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
                    | Buscar
                  </button>
                </div>
              </div>
            </form>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTableEsp" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Tarjeta</th>
                    <th>Valor</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Fecha</th>
                    <th>Ticket</th>
                    <th>Valor</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
                  <?php foreach ($this->pagos as $key => $value) { ?>
                  <tr>
                    <td><?php echo $value->getFecha()->format('d/m/Y'); ?></td>
                    <td><?php echo $value->getTarjeta()->getRfid(); ?></td>
                    <td><?php echo $value->getValor(); ?></td>
                    <td></td>
                  </tr>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>


</div>