<div class="container-fluid">

  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Registro de Otros Pagos</h6>
    </div>
    <div class="card-body">
      <form>
        <div class="form-row">
        <div class="form-group col-md-6">
            <label>Documento</label>
            <input name="documento" type="text" class="form-control" maxlength="10" autocomplete="off" id="documento">
          </div>
          <div class="form-group col-md-6">
            <label>Tipo Pago</label>
            <?php echo $this->combobox("tipoSancion", "Seleccione...", $this->tipoSanciones, "", "getId", "getDescripcion", "class='form-control show-tick' data-live-search='true' required id='tipoSancion'","getValor"); ?>
          </div>
          </div>
        
      </form>
    </div>
  </div>

  <div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Informaci&oacute;n de Pago Otro</h6>
  </div>
    <div class="card-body">
      <form class="formPagoSancion" method="post">
        <input type="hidden" name="guardar" value="1">
        <input type="hidden" name="documento" value="">
        <input type="hidden" name="tipoSancion" value="">

        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Total a Pagar</label>
            <input 
              name="totalPagar" 
              type="text" 
              class="form-control text-left" 
              data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 
              'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'" readonly>
            <input type="hidden" name="totalPagarNumero" value="">
          </div>
          <div class="form-group col-md-4">
            <label>Recibido</label>
            <input 
              name="recibido" 
              type="text" 
              class="form-control text-left" 
              data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 
              'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'" required>
              <input type="hidden" name="recibidoNumero" value="">
          </div>
          <div class="form-group col-md-4">
            <label>A Devolver</label>
            <input 
              name="devolver" 
              type="text" 
              class="form-control text-left" 
              data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 
              'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'" readonly>
              <input type="hidden" name="devolverNumero" value="">
          </div>
        </div>
        <div class="float-right">
          <button type="submit" class="btn btn-primary">Registrar Pago</button>
        </div>
      </form>
    </div>
  </div>

</div>

</div>