<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Ingreso Parqueadero</h1>
  <div class="row">
    <div class="col-xl-4 col-md-4 mb-4">
      <a href="<?php echo BASE_URL ?>ingreso/registrar/1/">
        <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-lg font-weight-bold text-primary text-uppercase mb-1">Automovil</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-car-side fa-5x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-4 col-md-4 mb-4">
      <a href="<?php echo BASE_URL ?>ingreso/registrar/2/">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-lg font-weight-bold text-primary text-uppercase mb-1">Motocicleta</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-biking fa-5x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-4 col-md-4 mb-4">
      <a href="<?php echo BASE_URL ?>ingreso/registrar/3/">
        <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-lg font-weight-bold text-primary text-uppercase mb-1">Bicicleta</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-bicycle fa-5x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    <div class="card-body">
      <form method="post" action="<?php echo BASE_URL ?>ingreso/registrarTarjeta/">
        <div class="input-group mb-3">
          <input name="tarjeta" type="text" class="form-control form-control-lg" placeholder="Registrar Tarjeta">
          <div class="input-group-append">
            <button class="btn btn-success btn-lg" type="submit">Registrar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /.container-fluid -->

</div>