<div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Listado de Clientes</h1>
        <!-- DataTales Example -->

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <div class="float-sm-right">
              <a href="<?php echo BASE_URL ?>cliente/agregar/" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                  <i class="fas fa-check"></i>
                </span>
                <span class="text">Registrar Cliente</span>
              </a>
            </div>
          </div>
          <div class="card-body">
            <?php if(isset($this->datos) && count($this->datos)){?>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTableEsp" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Documento</th>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Tipp Cliente</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Documento</th>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Tipp Cliente</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
                  <?php foreach ($this->datos as $key => $value) { ?>
                  <tr>
                    <td><?php echo $value->getDocumento(); ?></td>
                    <td><?php echo $value->getNombre(); ?></td>
                    <td><?php echo $value->getTelefono(); ?></td>
                    <td><?php echo $value->getEmail(); ?></td>
                    <td><?php echo $value->getTipocliente()->getDescripcion(); ?></td>
                    <td class="text-center">
                      <a title="Actualizar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>actualizar/<?php echo $value->getId(); ?>/"><i class="fas fa-edit"></i></a>
                    </td>
                  </tr>
                  <?php } ?>
                </tbody>
              </table>
            </div>
            <?php }else{ ?>
              <div class="alert alert-warning" role="alert">
               No hay clientes registrados.
              </div>
            <?php } ?>
          </div>
        </div>

      </div>


</div>