<div class="container-fluid">

  <div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Generar Reportes</h6>
  </div>
    <div class="card-body">
      <form class="needs-validation" novalidate method="post"> 
        <input type="hidden" name="guardar" value="1">
        <div class="form-row">
          <div class="form-group col-md-12">
            <label>Reporte</label>
            <select name="reporte" class="form-control" required>
              <option value="">Seleccione...</option>
              <option value="1">Reporte Diario</option>
	            <option value="2">Reporte Pases Cortesia</option>
              <option value="3">Reporte Informaci&oacute;n Tarjetas RFID</option>
	            <option value="4">Reporte Pago Mensualidades</option>
              <option value="10">Archivo Plano</option>
            </select>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Fecha Inicio</label>
	           <input 
              name="fechaIni" 
              type="text" 
              class="form-control datepicker" 
              data-date-format="dd/mm/yyyy"
              autocomplete="off"
              value="<?php echo $this->fecha ?>" 
              required >
          </div>
          <div class="form-group col-md-6">
            <label>Fecha Fin</label>
             <input 
              name="fechaFin" 
              type="text" 
              class="form-control datepicker" 
              data-date-format="dd/mm/yyyy"
              autocomplete="off"
              value="<?php echo $this->fecha ?>" 
              required >
          </div>
        </div>

        <div class="float-right">
          <button type="submit" class="btn btn-primary" >Generar</button> 
        </div>
      </form>
    </div>
  </div>

</div>

</div>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>