<div class="container-fluid">

  <div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Cambiar Clave</h6>
  </div>
    <div class="card-body">
      <form class="needs-validation" novalidate method="post"> 
        <input type="hidden" name="guardar" value="1">
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Clave Actual</label>
            <input name="actual" type="password" class="form-control" value="" required>
          </div>
          <div class="form-group col-md-4">
            <label>Nueva Clave</label>
            <input name="nueva" type="password" class="form-control" value="" required>
          </div>
          <div class="form-group col-md-4">
            <label>Repetir Clave</label>
            <input name="repetida" type="password" class="form-control" value="" required>
          </div>
        </div>

        <p class="text-right comentario">
          Los campos marcados con <span class="span">*</span> son obligatorios.
        </p>
        <div class="float-right">
          <button type="submit" class="btn btn-primary" >Cambiar Clave </button> 
          <a class="btn btn-primary" href="<?php echo BASE_URL; ?>">Cancelar</a>
        </div>
      </form>
    </div>
  </div>

</div>

</div>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>